### PR TITLE
Add '/English' option to dism.exe (Fix #11)

### LINKED ISSUE #11: Test-TargetResource always failes non-English OS
If you are using non english version of the Windows, Test-TargetResource always failes.

This issue caused by  [the code](https://github.com/PowerShell/xDismFeature/blob/3a9638a59bc07cfc126bf5704e9e5f39f575033a/DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1#L113)
``` Powershell
$DismGetFeatures = & dism.exe /Online /Get-Features
```

For fix this issue, Please add '/English' option.
``` Powershell
$DismGetFeatures = & dism.exe /Online /Get-Features /English
```

### PR DESCRIPTION
**Pull request by Amedama96**
Fixes #11

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14)

### CODE REVIEW

**Comment by johlju** [comment]
Sorry that nobody haven't reviewed this for so long!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdismfeature/14#-LCiAQcjApsJKfnXffhF:-LCiAQcjApsJKfnXffhG:b-7dcwte) (no related file):*
Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue.

---

*[DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1, line 113 at r2](https://reviewable.io/reviews/powershell/xdismfeature/14#-LCiAVLL-xnQR5slqUXr:-LCiAVLL-xnQR5slqUXs:b7hfp5d) ([raw file](https://github.com/powershell/xdismfeature/blob/5576de2444cec06497a89030f91814ef03e591f0/DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1#L113)):*
> ```PowerShell
> function Get-DismFeatures
> {
>     $DismGetFeatures = & dism.exe /Online /Get-Features /English
> ```

There is no limitation to this argument in different OS? It works from Windows Server 2008 R2 and above?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14#-:-LCiAeO51i3Y1yZhrdX7:b-fy6ziu)*

**Comment by Amedama96** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdismfeature/14#-LCiAQcjApsJKfnXffhF:-LCiibBk9Q72AvCg_i_b:b-drs700) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue.
</blockquote></details>

I added description to the change log in the README.md.
Please review it.

---

*[DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1, line 113 at r2](https://reviewable.io/reviews/powershell/xdismfeature/14#-LCiAVLL-xnQR5slqUXr:-LCiivJv4Fu7InrDt5Qd:bhn2kld) ([raw file](https://github.com/powershell/xdismfeature/blob/5576de2444cec06497a89030f91814ef03e591f0/DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1#L113)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There is no limitation to this argument in different OS? It works from Windows Server 2008 R2 and above?
</blockquote></details>

I have confirmed that the `/English` arguments are compatible with all of the following operating systems.
* Windows Server 2008 R2 SP1
* Windows Server 2012
* Windows Server 2012 R2
* Windows Server 2016
* Windows Server version 1709
* Windows 7 SP1
* Windows 8.1
* Windows 10 version 1703
* Windows 10 version 1709
* Windows 10 version 1803
* Windows 10 Insider Preview Build 17666

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdismfeature/14#-LCiAQcjApsJKfnXffhF:-LCn8xIU2sMllQ-ZOewN:b41unac) (no related file):*
<details><summary><i>Previously, Amedama96 (Amedama) wrote…</i></summary><blockquote>

I added description to the change log in the README.md.
Please review it.
</blockquote></details>

Thanks for confirming that it works on all those OS'es.  This looks good now. Just one more thing.  This is a very small change, but would you be up to creating a unit test, at least for the code that was change, the helper function `Get-DismFeatures` (not the entire resource)?
Let me know if you are up to it. :slightly_smiling_face: 

There are no unit test in this repo yet, so that will be the first, and should be created at`\Tests\Unit\MSFT_xDismFeature.Tests.ps1`. 
Template; https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14)*

**Comment by Amedama96** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdismfeature/14#-LCiAQcjApsJKfnXffhF:-LCr1-TD8gaYdkFfnki5:bkjdum3) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Thanks for confirming that it works on all those OS'es.  This looks good now. Just one more thing.  This is a very small change, but would you be up to creating a unit test, at least for the code that was change, the helper function `Get-DismFeatures` (not the entire resource)?
Let me know if you are up to it. :slightly_smiling_face: 

There are no unit test in this repo yet, so that will be the first, and should be created at`\Tests\Unit\MSFT_xDismFeature.Tests.ps1`. 
Template; https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1
</blockquote></details>

Thank you for review.
I tried creating unit tests.
In order to make test easier, I extracted the code calling dism.exe into a new function `Invoke-Dism`,  is there a problem?
Please tell me what you think.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14)*

**Comment by johlju** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/powershell/xdismfeature/14#-LCiAQcjApsJKfnXffhF:-LD1TgzlDgOS40DgdmuN:bksri7m) (no related file):*
<details><summary><i>Previously, Amedama96 (Amedama) wrote…</i></summary><blockquote>

Thank you for review.
I tried creating unit tests.
In order to make test easier, I extracted the code calling dism.exe into a new function `Invoke-Dism`,  is there a problem?
Please tell me what you think.
</blockquote></details>

Awesome work with the tests, you got 97% coverage! Having a wrapper for dism.exe works absolutely!

---

*[README.md, line 35 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1Y5afEyITibk3O8UT:-LD1Y5afEyITibk3O8UU:b-mnkldc) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/README.md#L35)):*
> ```Markdown
> ### Unreleased
> 
> * Added unit test
> ```

Non-blocking (this is optional): After each entry that you resolved you maybe add your name to those if you'd like.

```
* Added unit test. [Name/Alias (@github_account)](https://github.com/github_account) 
```

See example here: https://github.com/PowerShell/SqlServerDsc/blob/dev/CHANGELOG.md

---

*[DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1, line 71 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1XZ-V3oI9cviw_zDN:-LD1XZ-V3oI9cviw_zDO:b2iqt96) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1#L71)):*
> ```
> Invoke-Dism $dismParameters
> ```

We should use named parameters so `Invoke-Dism -Argument $dismParameters`.  See next comment too about `$Argument`.

Throughout.

---

*[DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1, line 140 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1XD5KABr_oNS6sPmG:-LD1XD5KABr_oNS6sPmH:b-tcgbqh) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1#L140)):*
> ```
> $DismParameters
> ```

Non-blocking nitpick: Maybe `$Argument` would be better since it is an .exe? 

---

*[Tests/Unit/MSFT_xDismFeature.Tests.ps1, line 73 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1SjDH-ZhSzwiqyv1y:-LD1SjDH-ZhSzwiqyv1z:b8k0drw) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/Tests/Unit/MSFT_xDismFeature.Tests.ps1#L73)):*
> ```
> $GetTargetResult
> ```

$getTargetResult (lower-case 'g'). Throughout.

---

*[Tests/Unit/MSFT_xDismFeature.Tests.ps1, line 195 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1ZOWS7S4oNh3mnipr:-LD1ZOWS7S4oNh3mnips:bj3bctj) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/Tests/Unit/MSFT_xDismFeature.Tests.ps1#L195)):*
> ```
> $TestTargetResult
> ```

$testTargetResult (lower-case 't'). Throughout.

---

*[Tests/Unit/MSFT_xDismFeature.Tests.ps1, line 230 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1ZRuC7RCsIdsf3BXk:-LD1ZRuC7RCsIdsf3BXl:bb0v1le) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/Tests/Unit/MSFT_xDismFeature.Tests.ps1#L230)):*
> ```
> $GetDismFeaturesResult
> ```

$getDismFeaturesResult (lower-case 'g'). Throughout.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14)*

**Comment by Amedama96** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1, line 71 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1XZ-V3oI9cviw_zDN:-LD28TjXCpOZOR2zAsap:bt2vr1b) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1#L71)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Invoke-Dism $dismParameters
> ```

We should use named parameters so `Invoke-Dism -Argument $dismParameters`.  See next comment too about `$Argument`.

Throughout.
</blockquote></details>

Fixed.

---

*[Tests/Unit/MSFT_xDismFeature.Tests.ps1, line 73 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1SjDH-ZhSzwiqyv1y:-LD28WC20CxXkSfYY5aV:bt2vr1b) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/Tests/Unit/MSFT_xDismFeature.Tests.ps1#L73)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $GetTargetResult
> ```

$getTargetResult (lower-case 'g'). Throughout.
</blockquote></details>

Fixed.

---

*[Tests/Unit/MSFT_xDismFeature.Tests.ps1, line 195 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1ZOWS7S4oNh3mnipr:-LD28XX75Zitz16269RF:bt2vr1b) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/Tests/Unit/MSFT_xDismFeature.Tests.ps1#L195)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $TestTargetResult
> ```

$testTargetResult (lower-case 't'). Throughout.
</blockquote></details>

Fixed.

---

*[Tests/Unit/MSFT_xDismFeature.Tests.ps1, line 230 at r4](https://reviewable.io/reviews/powershell/xdismfeature/14#-LD1ZRuC7RCsIdsf3BXk:-LD28YAU-WFHt8jpxu51:bt2vr1b) ([raw file](https://github.com/powershell/xdismfeature/blob/1161c211e2c30e8768798ecbe76b0b601ad09dbb/Tests/Unit/MSFT_xDismFeature.Tests.ps1#L230)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $GetDismFeaturesResult
> ```

$getDismFeaturesResult (lower-case 'g'). Throughout.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdismfeature/14#-:-LD2Bnov95A8ZKruiWBl:bnfp4nl)*

**Comment by johlju** [comment]
@Amedama96 Awesome work! Thank you! 😃

**Pull request merged**
