### PR TITLE
Add dism.exe error handling and EnableAllParentFeatures parameter

### PR DESCRIPTION
**Pull request by mgr32**
When trying to enable a child feature when a parent feature is disabled, xDismFeature fails silently (reporting success). This pull request addresses 2 issues - errors not being handled (exit code not checked) and no ability to pass '/All' parameter to dism.exe.

Consider following example:

```powershell
Configuration Test {
    Import-DSCResource -ModuleName xDismFeature

    xDismFeature IISParent {
        Name = 'IIS-HealthAndDiagnostics'
        Ensure = 'Absent'
    }

    xDismFeature IISChild {
        Name = 'IIS-HttpLogging'
        Ensure = 'Present'
        DependsOn = '[xDismFeature]IISParent'
    }
}

Test -OutputPath .\Test
Start-DscConfiguration -Path .\Test -Wait -Verbose -Force

dism /online /get-featureinfo /FeatureName:IIS-HttpLogging
```

The above code runs successfully, but does not install IIS-HttpLogging, because it depends on absent IIS-HealthAndDiagnostics:
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalC
onfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer x with user sid S-1-5-21-4222474-1288197275-456279356-8911.
VERBOSE: [x]: LCM:  [ Start  Set      ]
VERBOSE: [x]: LCM:  [ Start  Resource ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ Start  Test     ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ End    Test     ]  [[xDismFeature]IISParent]  in 1.1720 seconds.
VERBOSE: [x]: LCM:  [ Skip   Set      ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ End    Resource ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ Start  Resource ]  [[xDismFeature]IISChild]
VERBOSE: [x]: LCM:  [ Start  Test     ]  [[xDismFeature]IISChild]
VERBOSE: [x]: LCM:  [ End    Test     ]  [[xDismFeature]IISChild]  in 1.0470 seconds.
VERBOSE: [x]: LCM:  [ Start  Set      ]  [[xDismFeature]IISChild]
VERBOSE: [x]: LCM:  [ End    Set      ]  [[xDismFeature]IISChild]  in 1.8280 seconds.
VERBOSE: [x]: LCM:  [ End    Resource ]  [[xDismFeature]IISChild]
VERBOSE: [x]: LCM:  [ End    Set      ]    in  5.5406 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 4.498 seconds

Deployment Image Servicing and Management tool
Version: 6.3.9600.17031

Image Version: 6.3.9600.17031

Feature Information:

Feature Name : IIS-HttpLogging
Display Name : HTTP Logging
Description : Enables logging of Web site activity for this server
Restart Required : Possible
State : Disabled
```

After applying this pull request, '/All' parameter will be passed to dism.exe by default, which will make the above scenario work (IIS-HttpLogging will be installed). For scenarios where this is not desired (old Windows?), new 'EnableAllParentFeatures' parameter (which defaults to $true) can be set to $false. For the above example, this will result in properly logged exception:

```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalC
onfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer x with user sid S-1-5-21-4222474-1288197275-456279356-8911.
VERBOSE: [x]: LCM:  [ Start  Set      ]
VERBOSE: [x]: LCM:  [ Start  Resource ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ Start  Test     ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ End    Test     ]  [[xDismFeature]IISParent]  in 1.5940 seconds.
VERBOSE: [x]: LCM:  [ Start  Set      ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ End    Set      ]  [[xDismFeature]IISParent]  in 3.2340 seconds.
VERBOSE: [x]: LCM:  [ End    Resource ]  [[xDismFeature]IISParent]
VERBOSE: [x]: LCM:  [ Start  Resource ]  [[xDismFeature]IISChild]
VERBOSE: [x]: LCM:  [ Start  Test     ]  [[xDismFeature]IISChild]
VERBOSE: [x]: LCM:  [ End    Test     ]  [[xDismFeature]IISChild]  in 1.1100 seconds.
VERBOSE: [x]: LCM:  [ Start  Set      ]  [[xDismFeature]IISChild]
VERBOSE: [x]: LCM:  [ End    Set      ]  [[xDismFeature]IISChild]  in 1.6400 seconds.
PowerShell DSC resource MSFT_xDismFeature  failed to execute Set-TargetResource functionality with error message: dism.exe failed with 
code 50. Output:  Error: 50  The operation is complete but IIS-HttpLogging feature was not enabled. A required parent feature may not be 
enabled. You can use the /enable-feature /all option to automatically enable each parent feature from the following list. If the parent 
feature(s) are already enabled, refer to the log file for further diagnostics. IIS-HealthAndDiagnostics 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 8.121 seconds
```

### CODE REVIEW

**Comment by mgr32** [comment]
Powershell ISE is evil - it converted MSFT_xDismFeature.schema.mof to UTF-16 without saying anything, which made build fail. Fixed in two more commits.

**Comment by TravisEz13** [comment]
It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

**Comment by TravisEz13** [comment]
Please resolve any merge conflicts.  Instructions per GitHub:

Step 1: From your project repository, check out a new branch and test the changes.
```
git checkout -b mgr32-dev dev
git pull https://github.com/mgr32/xDismFeature.git dev
```
Step 2: Merge the changes and update on GitHub.
```
git checkout dev
git merge --no-ff mgr32-dev
git push origin dev
```

**Comment by TravisEz13** [comment]
If there is no update of the pull request within 7 days, we will close the pull request.  After that, if you have an update, feel free to reopen the pull request or a new pull request.

**Comment by TravisEz13** [comment]
Filed #8 for this
Closing because the pull request has not been updated for feedback given for 21 days.  Once you update the code, please feel free to reopen the pull request.  Thanks, Travis.

**Pull request closed without merging**
